<?php
session_start();
if (!isset($_SESSION['username'])) {
    echo "<script>alert('Please login first'); window.location.href='login.php';</script>";
    exit();
}


$host = $_ENV['DB_HOST'];
$user = $_ENV['DB_USER'];
$pass = $_ENV['DB_PASS'];
$db   = $_ENV['DB_NAME'];
$port = $_ENV['DB_PORT'];

$conn = new mysqli($host, $user, $pass, $db, $port);

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}


if (!isset($_GET['product_id'])) {
    echo "<script>alert('No product selected'); window.location.href='products.php';</script>";
    exit();
}

$product_id = $_GET['product_id'];
$query = "SELECT * FROM product WHERE product_id = $product_id";
$result = mysqli_query($conn, $query);
if (mysqli_num_rows($result) == 0) {
    echo "<script>alert('Product not found'); window.location.href='products.php';</script>";
    exit();
}

$product = mysqli_fetch_assoc($result);
$username = $_SESSION['username'];
$invoice = "PROD" . rand(10000, 99999);
$price = $product['product_price'];
$cgst = round($price * 0.09);
$sgst = round($price * 0.09);
$total = $price + $cgst + $sgst;

function convertNumberToWords($number) {
    $f = new NumberFormatter("en", NumberFormatter::SPELLOUT);
    return ucwords($f->format($number));
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>PRODUCT INVOICE | TURFBOOKING SYSTEM</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="./gallery/favicon.png" type="image/x-icon">
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
  <style>
    @media print {
      .no-print {
        display: none;
      }
    }
  </style>
</head>
<body class="bg-gray-100 px-4 py-8">

<div class="max-w-2xl mx-auto bg-white shadow-md rounded-lg p-6 border border-gray-300">
  <h1 class="text-2xl font-bold text-center text-blue-700 mb-2">PRODUCT BILLING SYSTEM</h1>
  <p class="text-sm text-center text-gray-500 mb-4">Tax Invoice / Purchase Confirmation</p>

  <div class="flex justify-between text-sm mb-4">
    <div>
      <p><strong>Invoice No:</strong> <?= $invoice ?></p>
      <p><strong>Date:</strong> <?= date("d-m-Y") ?></p>
      <p><strong>User:</strong> <?= $username ?></p>
      <p><strong>Email:</strong> demo@gmail.com</p>
      <p><strong>Phone:</strong> 7990972794</p>
    </div>
    <div>
      <p><strong>Billing Address:</strong></p>
      <p><?= $username ?> SD</p>
      <p>SSSC, Maharashtra - 360410</p>
    </div>
  </div>

  <table class="w-full text-sm border mb-4">
    <thead class="bg-gray-100 text-gray-800">
      <tr>
        <th class="p-2 border">Product</th>
        <th class="p-2 border">Price</th>
        <th class="p-2 border">CGST</th>
        <th class="p-2 border">SGST</th>
        <th class="p-2 border">Total</th>
      </tr>
    </thead>
    <tbody class="text-center">
      <tr>
        <td class="p-2 border"><?= htmlspecialchars($product['product_name']) ?></td>
        <td class="p-2 border">₹<?= $price ?></td>
        <td class="p-2 border">₹<?= $cgst ?></td>
        <td class="p-2 border">₹<?= $sgst ?></td>
        <td class="p-2 border font-semibold text-green-600">₹<?= $total ?></td>
      </tr>
    </tbody>
  </table>

  <p class="text-sm mb-4"><strong>Payment Mode:</strong> COD</p>
  <p class="text-sm italic mb-6"><strong>Amount in Words:</strong> <?= convertNumberToWords($total) ?> Rupees Only</p>

  <div class="flex justify-between items-center mt-6">
    <div class="text-sm text-center">
      <img src="signature.png" alt="Signature" class="h-10 mx-auto">
      <p class="text-xs">Authorized Signature</p>
      <p class="text-xs text-gray-500">Prince Antala</p>
    </div>
    <div>
      <!-- QR Code Placeholder -->
      <img src="https://api.qrserver.com/v1/create-qr-code/?size=100x100&data=<?= $username ?>-<?= $invoice ?>" alt="QR Code">
    </div>
  </div>

  <p class="text-center text-xs text-gray-400 mt-6">Generated by PrinceAntala45</p>

  <div class="flex justify-center mt-6 gap-4 no-print">
    <button onclick="window.print()" class="bg-green-500 text-white px-5 py-2 rounded hover:bg-green-600">🖨️ Print Bill</button>
    <a href="products.php" class="bg-blue-500 text-white px-5 py-2 rounded hover:bg-blue-600">🏠 Go to Products</a>
  </div>
</div>

</body>
</html>
